import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/course.dart';

class PdfGenerator {
  static Future<void> generateAndPrint(List<Course> courses, double cgpa, int totalCredits) async {
    final pdf = pw.Document();

    // Organize data by semester just like the Home Screen
    final Map<String, List<Course>> semesterGroups = {};
    for (int y = 1; y <= 4; y++) {
      for (int s = 1; s <= 2; s++) {
        String key = "Year $y Semester $s";
        semesterGroups[key] = courses
            .where((c) => c.year == y && c.semester == s)
            .toList();
      }
    }

    // Create the PDF Page
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            // Header
            pw.Header(
              level: 0,
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('UNIMAS Software Engineering', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text('Unofficial Grade Report', style: const pw.TextStyle(fontSize: 18)),
                  pw.Divider(),
                ],
              ),
            ),
            
            pw.SizedBox(height: 10),
            
            // Summary Box
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(),
                color: PdfColors.grey200,
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Current CGPA: ${cgpa.toStringAsFixed(2)}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
                  pw.Text('Total Credits: $totalCredits', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Course List Table
            ...semesterGroups.entries.where((entry) => entry.value.isNotEmpty).map((entry) {
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 5),
                    child: pw.Text(entry.key, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                  ),
                  pw.Table.fromTextArray(
                    context: context,
                    border: null,
                    headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    headerDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    cellHeight: 25,
                    cellAlignments: {
                      0: pw.Alignment.centerLeft,
                      1: pw.Alignment.centerLeft,
                      2: pw.Alignment.center,
                      3: pw.Alignment.center,
                    },
                    headers: ['Code', 'Course Name', 'Credits', 'Grade'],
                    data: entry.value.map((c) => [
                      c.code, 
                      c.name, 
                      c.creditHours.toString(), 
                      c.grade ?? '-'
                    ]).toList(),
                  ),
                  pw.SizedBox(height: 15),
                ],
              );
            }).toList(),
            
            // Footer
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 20),
              child: pw.Text(
                'Generated by UNIMAS SE Grade Planner App', 
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
            ),
          ];
        },
      ),
    );

    // This opens the built-in phone sharing/printing dialog
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }
}